### ISSUE TITLE
Missing input label for submit button (slabel)

### ISSUE THREAD

**Issue by tobaco** [inspiredminds/contao-extended-form-fields#2]
I'm using Contao 4.9.10 and Contao Extended Form Fields.

Without the extension I can input/change the label of a submit button:

![Without extension](https://user-images.githubusercontent.com/68937/106137271-c4232f80-616a-11eb-9f32-0a172f70b84a.png)

With the extension this input field is missing:

![With extension](https://user-images.githubusercontent.com/68937/106137572-2d0aa780-616b-11eb-9948-87cc84d32a6c.png)

Thanks!

**Comment by fritzmg** [comment]
I am unable to reproduce the problem. I did find another issue though, for which I just released `2.0.1`. May be this somehow fixes your issue as well? Otherwise this must be due to another extension, because starting with `2.0.1` the extension does not touch the `submit` palette at all.

**Comment by tobaco** [comment]
thanks! I don't know, if it's because of your update or something else, but it seems to be fixed now. 🎉
