### ISSUE TITLE
Attribut disabled=„disabled"

### ISSUE THREAD

**Issue by van-berg** [inspiredminds/contao-extended-form-fields#3]
Wenn ich dem Textfeld des Attribut disabled=„disabled" gebe, bekomme ich im Frontend trotzdem eine Fehlermeldung. Sollten Formularfelder mit dem Attribut disabled nicht von der Validierung ausgeschlossen werden?

**Comment by fritzmg** [comment]
Hängt das überhaupt mit dieser Extension zusammen? Wie hast du das Attribut gesetzt?

**Comment by van-berg** [comment]
Ich habe [contao-conditionalformfields](https://github.com/terminal42/contao-conditionalformfields) dafür genutzt, um es nur beim erfüllen einer bestimmten Bedingung einzublenden bzw. das Attribut disabled zu setzten.
Mein Ziel ist es ein Eingabefeld zu kreieren, welches nur bestimmte Begriffe erlaubt aber auch komplett leer bleiben darf. Das funktioniert bei mir bislang nicht.

**Comment by fritzmg** [comment]
Hm, verstehe. Die Conditional Form Fields Extension hebelt das dann für die jeweiligen Formulare selbst aus. Nur die Conditional Form Fields Extension weiß natürlich nichts von den zusätzlichen Überprüfungen anderer Extensions - und die Extended Form Fields Extension weiß auch nichts von den Disabled Fields der Conditional Form Fields Extension.

**Comment by fritzmg** [comment]
> Mein Ziel ist es ein Eingabefeld zu kreieren, welches nur bestimmte Begriffe erlaubt aber auch komplett leer bleiben darf. Das funktioniert bei mir bislang nicht.

Hier habe ich in Version 2.3.3 nun eine Anpassung gemacht. Nun wird bei Feldern, die nicht Pflicht sind, die erlaubte Liste an Wörtern nicht mehr überprüft, wenn der Wert leer ist.
