### ISSUE TITLE
Umgang mit conditional mandatory fields

### ISSUE THREAD

**Issue by ff1601com** [inspiredminds/contao-extended-form-fields#4]
Hallo,

wie geht die Erweiterung denn mit conditional mandatory fields um?
Beispiel:
- Ich habe ein Feld in Abhängigkeit eines anderen Feldes gesetzt. Es wird nur angezeigt, wenn mein Feld z.B bei einem Radio - Button einen bestimmten Wert einnimmt.
- Das in Abhängigkeit gezeigte Feld soll aber, wenn es denn angezeigt wird, unbedingt ausgefüllt werden; Ist also ein Pflichtfeld.

Kann die Erweiterung mit einem solchen Feld umgehen oder muss jedes conditional Field auf nicht mandatory gestellt werden?

#### Edit

Habe es eben getestet und das mandatory Field wird auch dann verlangt, wenn die Condition nicht eintrifft; Auch wenn es automatisch auf disabled gestellt wird.
Somit kann ich das Formular leider nicht absenden.

Gibt es hier eine Möglichkeit, dass Formular trotzdem abzusenden? Ggf. das Feld nur mandatory setzen, wenn es angezeigt wird?

**Comment by fritzmg** [comment]
I think you are in the wrong repository. Presumably you are talking about https://github.com/terminal42/contao-conditionalformfields/ ?

**Comment by fritzmg** [comment]
Possibly duplicate of #3

**Comment by ff1601com** [comment]
@fritzmg Oh sorry, you are right. I must have missclicked.
