### ISSUE TITLE
Standard-Wert aus Abfrage bei Feldtyp "Verstecktes Feld"

### ISSUE THREAD

**Issue by samuelheer** [inspiredminds/contao-extended-form-fields#5]
Hallo, 
beim Feldtyp "verstecktes Feld" wird die Checkbox "Standard-Wert aus Anfrage" nicht angezeigt, da dem Feldtyp "Verstecktes Feld" die Palette "Experteneinstellungen" fehlt.

Für ein Projekt habe ich das Feld dafür in der Feldgruppe "Feldkonfiguration" angezeigt. Damit funktioniert mein Anwendungsfall, schöner, wäre es jedoch, wenn du es direkt in die Erweiterung mit aufnehmen kannst?

Vielen Dank und liebe Grüße

**Comment by fritzmg** [comment]
Fixed in `2.7.3`
